import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "..", "data", "jobs.json");

function iso(daysFromNow) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
}
function slugify(s) {
  return s.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-");
}
function id(n) {
  return `job_${n.toString().padStart(4, "0")}`;
}

const now = new Date().toISOString();

const jobs = [
  {
    title: "Maharashtra Police Constable Recruitment 2026",
    organization: "Maharashtra Police Department",
    department: "Home Department, Government of Maharashtra",
    advertisementNumber: "MAHA-POL/2026/07",
    totalVacancies: 8200,
    vacancyBreakdown: [
      { post: "Police Constable", category: "Open: 3200, OBC: 1800, SC: 900, ST: 700, EWS: 600", count: 7200 },
      { post: "Police Driver Constable", category: "Open: 500, OBC: 300, SC: 100, ST: 100", count: 1000 },
    ],
    location: { state: "Maharashtra", district: "State-wide", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["12th"],
      minAge: 18,
      maxAge: 28,
      ageRelaxation: "5 years relaxation for OBC/SC/ST, 10 years for PwBD candidates as per government norms.",
    },
    jobType: "government",
    salary: "₹29,200 – ₹92,300 (Pay Level 5)",
    applicationFee: "₹450 (Open/OBC/EWS), ₹350 (SC/ST)",
    dates: { startDate: iso(-10), lastDate: iso(12), examDate: iso(60) },
    featured: true,
    daysAgo: 10,
  },
  {
    title: "SSC CGL Combined Graduate Level Exam 2026",
    organization: "Staff Selection Commission",
    department: "Ministry of Personnel, Public Grievances and Pensions, Govt. of India",
    advertisementNumber: "SSC-CGL/2026/01",
    totalVacancies: 17727,
    vacancyBreakdown: [
      { post: "Assistant Audit Officer", category: "Open: 1400, OBC: 780, SC: 420, ST: 210, EWS: 350", count: 3160 },
      { post: "Inspector (Central Excise)", category: "Open: 2200, OBC: 1200, SC: 640, ST: 320, EWS: 550", count: 4910 },
      { post: "Junior Statistical Officer", category: "Open: 2900, OBC: 1600, SC: 860, ST: 430, EWS: 720", count: 6510 },
    ],
    location: { state: "All India", allIndia: true },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["graduate", "any_graduate"],
      minAge: 18,
      maxAge: 32,
      ageRelaxation: "As per Government of India norms for reserved categories.",
    },
    jobType: "government",
    salary: "₹35,400 – ₹1,12,400 (Pay Level 6/7)",
    applicationFee: "₹100 (Male, General/OBC); Free for Female/SC/ST/EWS/PwBD",
    dates: { startDate: iso(-20), lastDate: iso(5), examDate: iso(70) },
    featured: true,
    daysAgo: 20,
  },
  {
    title: "Zilla Parishad Pune - Anganwadi Sevika Bharti 2026",
    organization: "Zilla Parishad Pune",
    department: "Women & Child Development Department",
    advertisementNumber: "ZP-PUNE/WCD/2026/03",
    totalVacancies: 145,
    vacancyBreakdown: [{ post: "Anganwadi Sevika", category: "Open: 60, OBC: 35, SC: 20, ST: 18, EWS: 12", count: 145 }],
    location: { state: "Maharashtra", district: "Pune", allIndia: false },
    eligibility: {
      genders: ["female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["10th", "12th"],
      minAge: 18,
      maxAge: 40,
    },
    jobType: "government",
    salary: "Honorarium ₹10,000 per month",
    applicationFee: "₹200",
    dates: { startDate: iso(-5), lastDate: iso(20) },
    featured: false,
    daysAgo: 5,
  },
  {
    title: "Indian Army Agniveer Recruitment Rally 2026",
    organization: "Indian Army",
    department: "Ministry of Defence, Government of India",
    advertisementNumber: "ARMY/AGNIVEER/2026/PUNE",
    totalVacancies: 4000,
    vacancyBreakdown: [
      { post: "Agniveer General Duty", category: "Open to all categories", count: 2600 },
      { post: "Agniveer Technical", category: "Open to all categories", count: 1400 },
    ],
    location: { state: "Maharashtra", district: "Pune", allIndia: false },
    eligibility: {
      genders: ["male"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["10th", "12th"],
      minAge: 17,
      maxAge: 21,
    },
    jobType: "government",
    salary: "₹30,000 per month (package, first year)",
    applicationFee: "Nil",
    dates: { startDate: iso(-15), lastDate: iso(3) },
    featured: true,
    daysAgo: 15,
  },
  {
    title: "IBPS Probationary Officer (PO) Recruitment 2026",
    organization: "Institute of Banking Personnel Selection",
    department: "Public Sector Banks",
    advertisementNumber: "IBPS-PO/2026/13",
    totalVacancies: 3489,
    vacancyBreakdown: [{ post: "Probationary Officer", category: "Open: 1400, OBC: 780, SC: 520, ST: 260, EWS: 350", count: 3489 }],
    location: { state: "All India", allIndia: true },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["graduate", "any_graduate"],
      minAge: 20,
      maxAge: 30,
    },
    jobType: "government",
    salary: "₹48,480 – ₹85,920",
    applicationFee: "₹850 (Gen/OBC/EWS), ₹175 (SC/ST/PwBD)",
    dates: { startDate: iso(-2), lastDate: iso(25), examDate: iso(55) },
    featured: false,
    daysAgo: 2,
  },
  {
    title: "Tata Consultancy Services - Graduate Trainee Hiring 2026",
    organization: "Tata Consultancy Services (TCS)",
    department: "Corporate Recruitment",
    advertisementNumber: "TCS-NQT/2026/06",
    totalVacancies: 2500,
    vacancyBreakdown: [{ post: "Assistant System Engineer", category: "Open to all candidates", count: 2500 }],
    location: { state: "Maharashtra", district: "Mumbai", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["engineering", "graduate"],
      minAge: 21,
      maxAge: 27,
    },
    jobType: "private",
    salary: "₹3.36 – 7 LPA",
    applicationFee: "Nil",
    dates: { startDate: iso(-8), lastDate: iso(18) },
    featured: true,
    daysAgo: 8,
  },
  {
    title: "Maharashtra State Public Service Commission - Civil Judge 2026",
    organization: "Maharashtra Public Service Commission (MPSC)",
    department: "Law & Judiciary Department",
    advertisementNumber: "MPSC/JUD/2026/02",
    totalVacancies: 118,
    vacancyBreakdown: [{ post: "Civil Judge Junior Division", category: "Open: 48, OBC: 27, SC: 16, ST: 12, EWS: 15", count: 118 }],
    location: { state: "Maharashtra", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["law"],
      minAge: 21,
      maxAge: 35,
    },
    jobType: "government",
    salary: "₹77,840 – ₹1,36,520",
    applicationFee: "₹600",
    dates: { startDate: iso(-30), lastDate: iso(-2) },
    featured: false,
    daysAgo: 30,
  },
  {
    title: "AIIMS Nursing Officer Recruitment 2026",
    organization: "All India Institute of Medical Sciences",
    department: "Ministry of Health & Family Welfare",
    advertisementNumber: "AIIMS/NURSE/2026/09",
    totalVacancies: 964,
    vacancyBreakdown: [{ post: "Nursing Officer", category: "Open: 390, OBC: 220, SC: 130, ST: 80, EWS: 144", count: 964 }],
    location: { state: "All India", allIndia: true },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["medical", "graduate"],
      minAge: 21,
      maxAge: 30,
    },
    jobType: "government",
    salary: "₹44,900 – ₹1,42,400",
    applicationFee: "₹1500 (Gen/OBC/EWS), ₹1200 (SC/ST)",
    dates: { startDate: iso(-6), lastDate: iso(9) },
    featured: false,
    daysAgo: 6,
  },
  {
    title: "Nagpur Municipal Corporation - Junior Clerk Bharti 2026",
    organization: "Nagpur Municipal Corporation",
    department: "General Administration",
    advertisementNumber: "NMC/GAD/2026/11",
    totalVacancies: 62,
    vacancyBreakdown: [{ post: "Junior Clerk", category: "Open: 25, OBC: 14, SC: 9, ST: 7, EWS: 7", count: 62 }],
    location: { state: "Maharashtra", district: "Nagpur", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["12th", "graduate"],
      minAge: 18,
      maxAge: 38,
    },
    jobType: "government",
    salary: "₹19,900 – ₹63,200",
    applicationFee: "₹300",
    dates: { startDate: iso(-1), lastDate: iso(0) },
    featured: false,
    daysAgo: 1,
  },
  {
    title: "Reliance Retail - Store Associate Internship Program 2026",
    organization: "Reliance Retail Ltd.",
    department: "Retail Operations",
    advertisementNumber: "RRL/INTERN/2026/22",
    totalVacancies: 800,
    vacancyBreakdown: [{ post: "Store Associate Intern", category: "Open to all candidates", count: 800 }],
    location: { state: "Maharashtra", district: "Pune", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["10th", "12th", "any_graduate"],
      minAge: 18,
      maxAge: 26,
    },
    jobType: "internship",
    salary: "₹12,000 per month stipend",
    applicationFee: "Nil",
    dates: { startDate: iso(-3), lastDate: iso(15) },
    featured: false,
    daysAgo: 3,
  },
  {
    title: "Indian Railways RRB Group D Recruitment 2026",
    organization: "Railway Recruitment Board",
    department: "Ministry of Railways, Government of India",
    advertisementNumber: "RRB/GRP-D/2026/04",
    totalVacancies: 32438,
    vacancyBreakdown: [{ post: "Track Maintainer / Helper / Porter", category: "Open: 13000, OBC: 7300, SC: 4800, ST: 2400, EWS: 3200", count: 32438 }],
    location: { state: "All India", allIndia: true },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["10th", "iti"],
      minAge: 18,
      maxAge: 33,
    },
    jobType: "government",
    salary: "₹18,000 (Pay Level 1)",
    applicationFee: "₹500 (Gen/OBC), ₹250 (SC/ST/EWS/Female refundable on appearing)",
    dates: { startDate: iso(-25), lastDate: iso(30) },
    featured: true,
    daysAgo: 25,
  },
  {
    title: "L&T Construction - Site Engineer (Diploma) Contract Hiring 2026",
    organization: "Larsen & Toubro Construction",
    department: "Infrastructure Projects",
    advertisementNumber: "LNT/CIVIL/2026/17",
    totalVacancies: 210,
    vacancyBreakdown: [{ post: "Site Engineer (Civil)", category: "Open to all candidates", count: 210 }],
    location: { state: "Maharashtra", district: "Nashik", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["diploma", "engineering"],
      minAge: 20,
      maxAge: 32,
    },
    jobType: "contract",
    salary: "₹22,000 – ₹30,000 per month",
    applicationFee: "Nil",
    dates: { startDate: iso(-4), lastDate: iso(2) },
    featured: false,
    daysAgo: 4,
  },
  {
    title: "Maharashtra Forest Department - Forest Guard Recruitment 2027 (Draft)",
    organization: "Maharashtra Forest Department",
    department: "Ministry of Environment & Forests",
    advertisementNumber: "MFD/2027/DRAFT",
    totalVacancies: 900,
    vacancyBreakdown: [{ post: "Forest Guard", category: "Open: 360, OBC: 200, SC: 130, ST: 110, EWS: 100", count: 900 }],
    location: { state: "Maharashtra", allIndia: false },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["12th"],
      minAge: 18,
      maxAge: 28,
    },
    jobType: "government",
    salary: "₹21,700 – ₹69,100",
    applicationFee: "₹400",
    dates: { startDate: iso(20), lastDate: iso(50) },
    featured: false,
    isDraft: true,
    daysAgo: 0,
  },
  {
    title: "Bank of Baroda - Specialist Officer (IT) Recruitment 2026",
    organization: "Bank of Baroda",
    department: "Human Resources Division",
    advertisementNumber: "BOB/SO-IT/2026/08",
    totalVacancies: 180,
    vacancyBreakdown: [{ post: "IT Specialist Officer", category: "Open: 72, OBC: 40, SC: 26, ST: 14, EWS: 28", count: 180 }],
    location: { state: "All India", allIndia: true },
    eligibility: {
      genders: ["male", "female"],
      categories: ["open", "obc", "sc", "st", "ews"],
      qualifications: ["engineering", "post_graduate"],
      minAge: 22,
      maxAge: 35,
    },
    jobType: "government",
    salary: "₹64,820 – ₹93,960",
    applicationFee: "₹850 (Gen/OBC/EWS), ₹175 (SC/ST)",
    dates: { startDate: iso(-1), lastDate: iso(1) },
    featured: false,
    daysAgo: 1,
  },
];

function buildJob(j, i) {
  const slug = slugify(`${j.title}-${j.organization}`);
  const status = j.isDraft ? "draft" : "published";
  return {
    id: id(i + 1),
    slug,
    title: j.title,
    organization: j.organization,
    department: j.department,
    advertisementNumber: j.advertisementNumber,
    logoUrl: "",
    totalVacancies: j.totalVacancies,
    vacancyBreakdown: j.vacancyBreakdown,
    location: j.location,
    eligibility: j.eligibility,
    jobType: j.jobType,
    salary: j.salary,
    applicationFee: j.applicationFee,
    dates: j.dates,
    links: {
      applyOnline: "https://example.gov.in/apply",
      officialNotification: "https://example.gov.in/notification.pdf",
      officialWebsite: "https://example.gov.in",
    },
    content: {
      eligibility: `<p>Candidates must fulfil the eligibility criteria for <strong>${j.title}</strong> as prescribed by ${j.organization}. Please read the official notification carefully before applying.</p>`,
      vacancyDetails: `<p>Total <strong>${j.totalVacancies.toLocaleString("en-IN")}</strong> vacancies are to be filled under this recruitment drive. Post-wise and category-wise break-up is given in the table above.</p>`,
      selectionProcess: `<ol><li>Online Application</li><li>Written / Computer Based Test</li><li>Physical Standard &amp; Efficiency Test (if applicable)</li><li>Document Verification</li><li>Medical Examination</li><li>Final Merit List</li></ol>`,
      howToApply: `<p>Eligible candidates may apply online through the official website before the last date. Keep scanned copies of photograph, signature and certificates ready before starting the application.</p>`,
      importantInstructions: `<ul><li>Read the official notification carefully before applying.</li><li>Ensure you meet the age and qualification criteria on the prescribed date.</li><li>Application fee once paid is non-refundable.</li><li>Keep a printout of the submitted application for future reference.</li></ul>`,
    },
    seo: {
      title: `${j.title} | Apply Online, Eligibility, Last Date`,
      metaDescription: `${j.title} - ${j.totalVacancies.toLocaleString("en-IN")} vacancies. Check eligibility, qualification, age limit, application fee and last date to apply online.`,
    },
    featured: !!j.featured,
    status,
    publishAt: null,
    createdAt: new Date(Date.now() - j.daysAgo * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - j.daysAgo * 86400000).toISOString(),
    views: Math.floor(Math.random() * 5000) + (j.featured ? 4000 : 200),
  };
}

const output = jobs.map(buildJob);
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(output, null, 2));
console.log(`Seeded ${output.length} jobs to ${OUT}`);
